---
- name: go_gen
  hosts: localhost
  connection: local
  tasks:


  - name: import_vars
    ansible.builtin.include_vars:
      file: acs_paths.yaml

  - name: Create main_ strings files
    ansible.builtin.template:
      src: go_main_strings.j2
      dest: "main_string.txt"

  - name: create folders for each path
    file:
      path: "../acs/base/{{ item | lower }}"
      state: directory
      mode: 0775
      recurse: true
    with_items: "{{ acs_paths }}"

  - name: Create base files
    ansible.builtin.template:
      src: go_base.j2
      dest: "../acs/base/{{ item | lower }}/{{ item | lower }}.go"
    with_items: "{{ acs_paths }}"

  - name: Create doc files
    ansible.builtin.template:
      src: go_doc.j2
      dest: "../acs/base/{{ item | lower }}/doc.go"
    with_items: "{{ acs_paths }}"


